<h1 align="center">Numpy in python</h1> 

NumPy is a Python library used for working with arrays and primarily for numerical and scientific computing. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

### Why Use NumPy?
1. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
2. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

### Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

### Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.



In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# 1d array

arr=[1,2,3,4,5]

np.array(arr)

array([1, 2, 3, 4, 5])

In [3]:
# 2d array 

my_mat=[[1,2,3],[4,5,6],[7,8,9]]

np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<h1 align="center">Below is some numpy methods for arrays</h1> 

### 1. arange() - to generate array just like range function

In [4]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.arange(0,11,2) # adding step size

array([ 0,  2,  4,  6,  8, 10])

### 2. zeros() - to generate array with zeros

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((5,5)) # zeroes 2-d matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 3. ones() - to generate array with ones

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### 4. eye() method - to make Identity matrix.

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 5. linspace() - to generate evenly spaced numbers over a specified interval. 

In [10]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

### 6. reshape() - It changes the dimension of array 


In [11]:
arr= np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
arr.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### 7. min() and max() methods on arrays

In [13]:
arr.max()

15

In [14]:
arr.min()

1

In [15]:
arr.argmax() # it returns index value of max element

14

### 8. dtype() - to get datatype of array

In [16]:
arr.dtype

dtype('int64')

### 9. random module

In [17]:
np.random.rand(5)

array([0.87872136, 0.81625519, 0.07247598, 0.43859111, 0.6490687 ])

In [18]:
np.random.rand(5,5)

array([[0.06252744, 0.90909601, 0.9945252 , 0.97198251, 0.55021319],
       [0.46475112, 0.36483885, 0.98340278, 0.78871029, 0.79768934],
       [0.27420923, 0.37889864, 0.13928105, 0.10682824, 0.46213929],
       [0.04127559, 0.93323464, 0.75608758, 0.45401346, 0.71536513],
       [0.63813447, 0.98395895, 0.06573721, 0.36417306, 0.28745334]])

In [19]:
np.random.randn(4,4)

array([[ 0.4443884 , -2.52701384,  0.78549518,  0.63378295],
       [-1.17557148, -0.23726883, -0.17219018,  0.76311058],
       [-0.05312551,  0.36463526, -1.41170246, -1.6306758 ],
       [-1.08675342, -0.11019095, -0.40017519,  0.33447072]])

In [20]:
np.random.randint(1,100,10)

array([23, 24, 10, 90, 48, 57,  7,  6, 82, 90])

### 10. matmul() or @ operator - for matrix multiplication.

In [25]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
What is Numpy?


In [26]:
np.matmul(arr1,arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [27]:
arr1 @ arr2

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

<h1 align="center">Numpy Indexing & Selection</h1> 


In [ ]:
arr=np.arange(1,11)
arr

In [ ]:
arr[0] # indexing with place

In [ ]:
arr[0:5] # indexing with start, stop

In [ ]:
arr[:] # indexing from star to end

In [ ]:
arr[5::2] # indexing from 5 to end with step=2

In [ ]:
arr[0:5]=100 # broadcasting on arrays
arr

### # Slice affects actual array can be seen below - 

<div class="alert alert-block alert-warning">
<b>Reason:</b> numpy do this is, because of memmory issues with very large arrays it don't make copies of array automatically.
</div>

In [ ]:
slice_of_arr=arr[0:6]
slice_of_arr

In [ ]:
arr # actual arr

In [ ]:
slice_of_arr[:]=99

In [ ]:
arr #arr got changed as seen

### # To avoid that we use copy() method specifically.

In [ ]:
arr_copy= arr.copy()
arr_copy

In [ ]:
arr_copy[:]=101
arr_copy

In [ ]:
arr # actual array didn't changed

### # Indexing of a 2-D array.

In [ ]:
arr_2d=np.arange(1,13).reshape(3,4)
arr_2d

In [ ]:
arr_2d[0][1] # array indexing using dounle braces.

In [ ]:
arr_2d[0,1] # array indexing using single braces.

### # Important slicing to grab sub-section of  2-D matrix.

In [ ]:
arr_2d[:2,2:4] 

In [ ]:
arr_2d[0:1]  # 1st row

In [ ]:
arr_2d[:,0:1] # 1st column

### # Conditional selection or slicing

In [ ]:
arr=np.arange(0,15)
arr

In [ ]:
arr>5 # gives a bool array

In [ ]:
exp=arr>5

In [ ]:
arr[exp] # filters array element

In [ ]:
arr

In [ ]:
arr[arr>3] # better way to write without variable

<h1 align="center">Numpy Operations</h1> 

- **Array with Array** 
- **Array with scalar** 
- **Universal array functions. (ufunc)**

### # Array with Array

In [ ]:
arr=np.arange(1,11)


In [ ]:
arr+arr

In [ ]:
arr*arr

In [ ]:
arr-arr

In [ ]:
arr+100 #array with scalar

In [ ]:
arr/arr

In [ ]:
arr/0

<div class="alert alert-block alert-danger">
<b>Error:</b> In general, anything divided by 0 will give pyhton error. However, numpy will not give error instead will give a warning and execute further as above and "inf" means infinity.
</div>

In [ ]:
np.sqrt(arr)  #universal array functions 

In [ ]:
np.exp(arr) # calculate exponential

In [ ]:
np.max(arr) # to get max element in array

@numpy notes by rajveer mehta

Review Questions to Check Your Comprehension
Try answering the following questions to test your understanding of the topics covered in this notebook:

1, What is a vector?
2, How do you represent vectors using a Python list? Give an example.
3, What is a dot product of two vectors?
4, Write a function to compute the dot product of two vectors.
5, What is Numpy?
6, How do you install Numpy?
7, How do you import the numpy module?
8, What does it mean to import a module with an alias? Give an example.
9, What is the commonly used alias for numpy?
10, What is a Numpy array?
11, How do you create a Numpy array? Give an example.
12, What is the type of Numpy arrays?
13, How do you access the elements of a Numpy array?
14, How do you compute the dot product of two vectors using Numpy?
15, What happens if you try to compute the dot product of two vectors which have different sizes?
16, How do you compute the element-wise product of two Numpy arrays?
17, How do you compute the sum of all the elements in a Numpy array?
18, What are the benefits of using Numpy arrays over Python lists for operating on numerical data?
19, Why do Numpy array operations have better performance compared to Python functions and loops?
20, Illustrate the performance difference between Numpy array operations and Python loops using an example.
21, What are multi-dimensional Numpy arrays?
22, Illustrate how you'd create Numpy arrays with 2, 3, and 4 dimensions.
23, How do you inspect the number of dimensions and the length along each dimension in a Numpy array?
24, Can the elements of a Numpy array have different data types?
25, How do you check the data types of the elements of a Numpy array?
26, What is the data type of a Numpy array?
27, What is the difference between a matrix and a 2D Numpy array?
28, How do you perform matrix multiplication using Numpy?
29, What is the @ operator used for in Numpy?
30, What is the CSV file format?
31, How do you read data from a CSV file using Numpy?
32, How do you concatenate two Numpy arrays?
33, What is the purpose of the axis argument of np.concatenate?
34, When are two Numpy arrays compatible for concatenation?
35, Give an example of two Numpy arrays that can be concatenated.
36, Give an example of two Numpy arrays that cannot be concatenated.
37, What is the purpose of the np.reshape function?
38, What does it mean to “reshape” a Numpy array?
39, How do you write a numpy array into a CSV file?
40, Give some examples of Numpy functions for performing mathematical operations.
41, Give some examples of Numpy functions for performing array manipulation.
42, Give some examples of Numpy functions for performing linear algebra.
43, Give some examples of Numpy functions for performing statistical operations.
44, How do you find the right Numpy function for a specific operation or use case?
45, Where can you see a list of all the Numpy array functions and operations?
46, What are the arithmetic operators supported by Numpy arrays? Illustrate with examples.
47, What is array broadcasting? How is it useful? Illustrate with an example.
48, Give some examples of arrays that are compatible for broadcasting.
49, Give some examples of arrays that are not compatible for broadcasting.
50, What are the comparison operators supported by Numpy arrays? Illustrate with examples.
51, How do you access a specific subarray or slice from a Numpy array?
52, Illustrate array indexing and slicing in multi-dimensional Numpy arrays with some examples.
53, How do you create a Numpy array with a given shape containing all zeros?
54, How do you create a Numpy array with a given shape containing all ones?
55, How do you create an identity matrix of a given shape?
56, How do you create a random vector of a given length?
57, How do you create a Numpy array with a given shape with a fixed value for each element?
58, How do you create a Numpy array with a given shape containing randomly initialized elements?
59, What is the difference between np.random.rand and np.random.randn? Illustrate with examples.
60, What is the difference between np.arange and np.linspace? Illustrate with examples.